---
version: "2"
services:
  bookstack:
    image: ghcr.io/linuxserver/bookstack
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL=http://bookstack.sis.ai
      - APP_LANG=zh_TW
      - DB_HOST=bookstack_db
      - DB_USER=bookstack
      - DB_PASS=synergiesai
      - DB_DATABASE=bookstackapp
      - GOOGLE_APP_ID=377671836758-akmkh6p3mll8lg61m889hkhjlv24r4ao.apps.googleusercontent.com
      - GOOGLE_APP_SECRET=jI8gi0nFfzZiUWYrBxDA8Q0k
      - WKHTMLTOPDF=/usr/bin/wkhtmltopdf
    volumes:
      - ./data:/config
    ports:
      - 6875:80
    restart: unless-stopped
    depends_on:
      - bookstack_db
  bookstack_db:
    image: ghcr.io/linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=synergiesai
      - TZ=Asia/Taipei
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=synergiesai
    volumes:
      - ./data:/config
    restart: unless-stopped
