version: '3.3'
services:
  prometheus-server:
    image: prom/prometheus:v2.22.2
    container_name: prometheus-server
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./etc/prometheus:/etc/prometheus
      - prometheus-volume:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles

volumes:
  prometheus-volume:

